server:
  port: 8899
spring:
  thymeleaf:
      prefix: classpath:/templates/
      check-template-location: true
      cache: false
      suffix: .html
      encoding: UTF-8
      content-type: text/html
      mode: HTML5

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/goblog?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    druid:
#      #监控统计拦截的filters
#      filter: stat
#      #mysql驱动
#      driver-class-name: com.mysql.jdbc.Driver
#      #基本属性
#      url: jdbc:mysql://127.0.0.1:3306/goblog?useUnicode=true&characterEncoding=UTF-8
#      username: root
#      password: root
#      #配置初始化大小/最小/最大
#      initial-size: 1
#      min-idle: 1
#      max-active: 20
#      #获取连接等待超时时间
#      max-wait: 60000
#      #间隔多久进行一次检测，检测需要关闭的空闲连接
#      time-between-eviction-runs-millis: 60000

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.iguxue.goblog.entity


  logging:
    level:
      com.seamax.bdsearch.dao: DEBUG

#mybatis:
#  mapper-locations: classpath:mapper/**/*.xml
#  type-aliases-package: cn.iguxue.goblog.entity


